      SUBROUTINE CLCONC(CC,CN,HU,HV,HW,TMUX,TMUY,TMUZ,XC,YC,ZC,
     $                  XCP,YCOS,YCOSP,GV,GX,GY,GZ,HH,HX,HDEP,QW,
     $                  INDP,INDU,INDV,INDW,LLWALL,LLWALP,KF,KH,KG,KP,
     $                  CCBCN,FU,FV,FW,SRCA,SRCB)
C======================================================================
C     塩素の輸送式のより新しい時刻の塩素量濃度を計算する
C       FU: X方向流束,FV: Y方向流束,FW: Z方向流束
C       CC: 新しい時刻の濃度(塩分.or.塩素量:‰)
C======================================================================
      IMPLICIT NONE
C
      INCLUDE 'DOMAIN.h'
      INCLUDE 'MODELI.h'
      INCLUDE 'MODELR.h'
      INCLUDE 'PROPTY.h'
      INCLUDE 'CP_NESTBC.h'
      INCLUDE 'MYCNST.h'
      INCLUDE 'CONSRV.h'
C
      REAL(8),INTENT(INOUT)::CN(MX,MY,MZ),CC(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::HDEP(MX,MY),HH(MX,MY),HX(MX,MY),QW(MX,MY)
      REAL(8),INTENT(INOUT)::HU(MX,MY,MZ),HV(MX,MY,MZ),HW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::TMUX(MX,MY,MZ),TMUY(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::XC(8,MX,MY),YC(8,MY),ZC(8,MZ)
      REAL(8),INTENT(IN)::XCP(8,MX,MY),YCOS(MY),YCOSP(MY)
      REAL(8),INTENT(INOUT)::GV(MX,MY,MZ),GX(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::GY(MX,MY,MZ),GZ(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::INDP(MX,MY,MZ),INDU(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::INDV(MX,MY,MZ),INDW(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::LLWALL(8,MLWALL),LLWALP(8,MLWALP)
      INTEGER,INTENT(INOUT)::KF(MX,MY),KH(MX,MY),KG(MX,MY),KP(MX,MY)
      REAL(8),INTENT(INOUT)::CCBCN(NXY,MZ,4)
      REAL(8),INTENT(INOUT)::FU(MX,MY,MZ),FV(MX,MY,MZ),FW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::TMUZ(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::SRCA(MX,MY,MZ),SRCB(MX,MY,MZ)
C
      INTEGER::I,J,K,LL
      INTEGER::NN=2,IZCAL=0
C
C      
      CALL CELLSC(CC,CN,GV,XC,YC,ZC,HX,HDEP,INDP,KH,KG)
      CALL CHKCNS(CN,SUMCC)
C
      CALL FLUXSX(FU,CC,HU,TMUX,GX,HDEP,HX,XC,ZC,INDP,INDU,LLWALL,
     $            KG,KP,KH,CCBCN,NN,DIFH,SCT,PARAMC)
C
      CALL FLUXSY(FV,CC,HV,TMUY,GY,HDEP,HX,YC,ZC,INDP,INDV,LLWALL,
     $            KG,KP,KH,CCBCN,NN,DIFH,SCT,PARAMC)
C
      CALL FLUXSZ(FW,CC,HW,TMUZ,GZ,ZC,INDP,INDW,LLWALL,
     $            KG,KP,KH,NN,DIFV,SCT,PARAMC,IZCAL)
C
C ... 板境界の流束を修正する
C
      LL=6+NN
      CALL FLUXPL(FU,FV,FW,LLWALP,LL)
C
C ... 新しい時刻の濃度を計算する
C
      CALL ZERCLR(SRCA,MXYZ,0.0D0)
      CALL ZERCLR(SRCB,MXYZ,0.0D0)
C
C ... 海面からの塩分欠損条件を処理する
C
      IF( LSURF.EQ.1 )
     $   CALL BCCSRF(SRCA,SRCB,FW,CC,HH,HX,HDEP,QW,XC,YC,ZC,GV,
     $              INDP,KF,KH,KG)
C
      CALL CLSNEW(CC,CN,FU,FV,FW,SRCA,SRCB,TMUZ,HH,
     $            XC,YC,ZC,XCP,YCOS,GV,GZ,
     $            INDP,INDU,INDV,KG,KP,KF,DIFV,SCT,0)
      CALL CHKVAL(CC,HH,HDEP,KF,33.0D0)
C
      RETURN
      END
