      SUBROUTINE CP_RCVNS2ML(UU_ML,VV_ML,WW_ML,TT_ML,CC_ML,X1_ML,X2_ML,
     1                       HH_ML,CSD_ML,ZBD_ML,BUF,
     2                       MX_ML,MY_ML,MZ_ML,
     3                       IEAS,IWES,JSOU,JNOR,KBOT,KTOP,
     4                       NESXM,NESXP,NESYM,NESYP,IFL)
C-----------------------------------------------------------------------
C     NS側で平均化した流速,潮位をMLで受信する
C       LTURB=3 : X1=Q2,X2=QL
C       LTURB=4 : X1=AK,X2=1.0D30
C-----------------------------------------------------------------------
C
      use mod_comm,only: comm_model
      IMPLICIT NONE
C
      INCLUDE  'MODELI.h'
      INCLUDE  'CP_NESTBC.h'
      INCLUDE  'CONNEC.h'
      INCLUDE  'mpif.h'
      INCLUDE  'GLOBAL.h'
C
      INTEGER,INTENT(INOUT)::MX_ML,MY_ML,MZ_ML
      INTEGER,INTENT(INOUT)::IEAS,IWES,JSOU,JNOR,KBOT,KTOP
      INTEGER,INTENT(INOUT)::NESXM,NESXP,NESYM,NESYP
      INTEGER,INTENT(INOUT)::IFL
C
      REAL(8),INTENT(INOUT)::UU_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::VV_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::WW_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::TT_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::CC_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::CSD_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::ZBD_ML(MX_ML,MY_ML)
      REAL(8),INTENT(INOUT)::X1_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::X2_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::HH_ML(MX_ML,MY_ML)
      REAL(8),INTENT(INOUT)::BUF(*)
C
      INTEGER::ISTAT(MPI_STATUS_SIZE)
C
      INTEGER::I,ICHILD,IERROR,IREQ,J,K,NCOUNT,NDATA
      INTEGER::N,NS,NE,ICHILN,JSS,JEE,ISS,IEE
C
C      ICHILD=IPECON(3,NRANK+1)
      NS = NUMPE(2,NRANK+1)
      NE = NS+NUMPE(1,NRANK+1)-1
C
C ... IFL = 1 UU_ML,VV_MLのみを受信する
      IF(IFL.EQ.1.OR.IFL.EQ.0) THEN
c ...................................
C
      NDATA=2*(IEAS-IWES-NESXM-NESXP)*(KTOP-KBOT+3)
      IF(NESXM.GT.0)
     &   NDATA=NDATA+(JNOR-JSOU-NESYM-NESYP+1)*(KTOP-KBOT+3)
      IF(NESXP.GT.0)
     &   NDATA=NDATA+(JNOR-JSOU-NESYM-NESYP+1)*(KTOP-KBOT+3)
C
      IF(NDATA.GT.0) THEN
C
      DO 140 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      IF(NESXM.GT.0) THEN
         JSS = JSOU+NESYM
         JEE = JNOR-NESYP
         IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
         IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
         DO 100 K=KBOT-1,KTOP+1
         DO 100 J=JSOU+NESYM,JNOR-NESYP
         NCOUNT=NCOUNT+1
         IF(IPECON(5,ICHILN+1).GE.0) GO TO 100
         IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 100
         UU_ML(IWES+NESXM-1,J,K)=BUF(NCOUNT)
  100    CONTINUE
      ENDIF
C
      IF(NESXP.GT.0) THEN
         JSS = JSOU+NESYM
         JEE = JNOR-NESYP
         IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
         IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
         DO 110 K=KBOT-1,KTOP+1
         DO 110 J=JSOU+NESYM,JNOR-NESYP
         NCOUNT=NCOUNT+1
         IF(IPECON(6,ICHILN+1).GE.0) GO TO 110
         IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 110
         UU_ML(IEAS-NESXP,J,K)=BUF(NCOUNT)
  110    CONTINUE
      ENDIF
C
      ISS = IWES+NESXM
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)-1
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 120 K=KBOT-1,KTOP+1
      DO 120 I=IWES+NESXM,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(4,ICHILN+1).GE.0) GO TO 120
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 120
      UU_ML(I,JSOU+NESYM,K)=BUF(NCOUNT)
  120 CONTINUE
C
      ISS = IWES+NESXM
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)-1
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 130 K=KBOT-1,KTOP+1
      DO 130 I=IWES+NESXM,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(7,ICHILN+1).GE.0) GO TO 130
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 130
      UU_ML(I,JNOR-NESYP,K)=BUF(NCOUNT)
  130 CONTINUE
  140 CONTINUE
      ENDIF
C
C ... VV_MLを受信する。
C
      NDATA=2*(JNOR-JSOU-NESYM-NESYP)*(KTOP-KBOT+3)
      IF(NESYM.GT.0)
     &   NDATA=NDATA+(IEAS-IWES-NESXM-NESXP+1)*(KTOP-KBOT+3)
      IF(NESYP.GT.0)
     &   NDATA=NDATA+(IEAS-IWES-NESXM-NESXP+1)*(KTOP-KBOT+3)
C
      IF(NDATA.GT.0) THEN
C
      DO 240 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      IF(NESYM.GT.0) THEN
         ISS = IWES+NESXM
         IEE = IEAS-NESXP
         IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
         IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
         DO 200 K=KBOT-1,KTOP+1
         DO 200 I=IWES+NESXM,IEAS-NESXP
         NCOUNT=NCOUNT+1
         IF(IPECON(4,ICHILN+1).GE.0) GO TO 200
         IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 200
         VV_ML(I,JSOU+NESYM-1,K)=BUF(NCOUNT)
  200    CONTINUE
      ENDIF
C
      IF(NESYP.GT.0) THEN
         ISS = IWES+NESXM
         IEE = IEAS-NESXP
         IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
         IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
         DO 210 K=KBOT-1,KTOP+1
         DO 210 I=IWES+NESXM,IEAS-NESXP
         NCOUNT=NCOUNT+1
         IF(IPECON(7,ICHILN+1).GE.0) GO TO 210
         IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 210
         VV_ML(I,JNOR-NESYP,K)=BUF(NCOUNT)
  210    CONTINUE
      ENDIF
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP-1
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)-1
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 220 K=KBOT-1,KTOP+1
      DO 220 J=JSOU+NESYM,JNOR-NESYP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(5,ICHILN+1).GE.0) GO TO 220
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 220
      VV_ML(IWES+NESXM,J,K)=BUF(NCOUNT)
  220 CONTINUE
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP-1
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 230 K=KBOT-1,KTOP+1
      DO 230 J=JSOU+NESYM,JNOR-NESYP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(6,ICHILN+1).GE.0) GO TO 230
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 230
      VV_ML(IEAS-NESXP,J,K)=BUF(NCOUNT)
  230 CONTINUE
  240 CONTINUE
      ENDIF
C
      END IF
C
C ... IFL = 2 (UU_ML,VV_ML)以外を受信
      IF(IFL.EQ.2.OR.IFL.EQ.0) THEN
C .....................................
C
C ... WW_MLを受信する。
C
      NDATA=2*(JNOR-JSOU-NESYM-NESYP+1)*(KTOP-KBOT+3)
     &     +2*MAX(0,IEAS-IWES-NESXM-NESXP-1)*(KTOP-KBOT+3)
C
      DO 340 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 300 K=KBOT-1,KTOP+1
      DO 300 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(5,ICHILN+1).GE.0) GO TO 300
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 300
      WW_ML(IWES+NESXM,J,K)=BUF(NCOUNT)
  300 CONTINUE
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 310 K=KBOT-1,KTOP+1
      DO 310 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(6,ICHILN+1).GE.0) GO TO 310
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 310
      WW_ML(IEAS-NESXP,J,K)=BUF(NCOUNT)
  310 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 320 K=KBOT-1,KTOP+1
      DO 320 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(4,ICHILN+1).GE.0) GO TO 320
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 320
      WW_ML(I,JSOU+NESYM,K)=BUF(NCOUNT)
  320 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 330 K=KBOT-1,KTOP+1
      DO 330 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(7,ICHILN+1).GE.0) GO TO 330
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 330
      WW_ML(I,JNOR-NESYP,K)=BUF(NCOUNT)
  330 CONTINUE
  340 CONTINUE
C
C ... HH_MLを受信する。
C
      NDATA=(NESXM+2)*(JNOR-JSOU+3)+(NESXP+2)*(JNOR-JSOU+3)
     &     +(NESYM+2)*MAX(0,IEAS-IWES-NESXM-NESXP-1)
     &     +(NESYP+2)*MAX(0,IEAS-IWES-NESXM-NESXP-1)
C
      DO 440 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
      JSS = JSOU-1
      JEE = JNOR+1
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      ISS = IWES-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      DO 400 J=JSOU-1,JNOR+1
      DO 400 I=IWES-1,IWES+NESXM
      NCOUNT=NCOUNT+1
      IF(J.LT.JSS.OR.J.GT.JEE) GO TO 400
      IF(ISS.GT.IWES+NESXM   ) GO TO 400
      HH_ML(I,J)=BUF(NCOUNT)
  400 CONTINUE
C
      JSS = JSOU-1
      JEE = JNOR+1
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      IEE = IEAS+1
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 410 J=JSOU-1,JNOR+1
      DO 410 I=IEAS-NESXP,IEAS+1
      NCOUNT=NCOUNT+1
      IF(J.LT.JSS.OR.J.GT.JEE) GO TO 410
      IF(IEE.LT.IEAS-NESXP   ) GO TO 410
      HH_ML(I,J)=BUF(NCOUNT)
  410 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      JSS = JSOU-1
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      DO 420 J=JSOU-1,JSOU+NESYM
      DO 420 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(I.LT.ISS.OR.I.GT.IEE) GO TO 420
      IF(JSS.GT.JSOU+NESYM   ) GO TO 420
      HH_ML(I,J)=BUF(NCOUNT)
  420 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      JEE = JNOR+1
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 430 J=JNOR-NESYP,JNOR+1
      DO 430 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(I.LT.ISS.OR.I.GT.IEE) GO TO 430
      IF(JEE.LT.JNOR-NESYP   ) GO TO 430
      HH_ML(I,J)=BUF(NCOUNT)
  430 CONTINUE
  440 CONTINUE
C
      IF(LTEMP.EQ.1) THEN
C ... TT_MLを受信する。
C
      NDATA=2*(JNOR-JSOU-NESYM-NESYP+1)*(KTOP-KBOT+3)
     &     +2*MAX(0,IEAS-IWES-NESXM-NESXP-1)*(KTOP-KBOT+3)
C
      DO 540 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 500 K=KBOT-1,KTOP+1
      DO 500 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(5,ICHILN+1).GE.0) GO TO 500
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 500
      TT_ML(IWES+NESXM,J,K)=BUF(NCOUNT)
  500 CONTINUE
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 510 K=KBOT-1,KTOP+1
      DO 510 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(6,ICHILN+1).GE.0) GO TO 510
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 510
      TT_ML(IEAS-NESXP,J,K)=BUF(NCOUNT)
  510 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 520 K=KBOT-1,KTOP+1
      DO 520 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(4,ICHILN+1).GE.0) GO TO 520
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 520
      TT_ML(I,JSOU+NESYM,K)=BUF(NCOUNT)
  520 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 530 K=KBOT-1,KTOP+1
      DO 530 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(7,ICHILN+1).GE.0) GO TO 530
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 530
      TT_ML(I,JNOR-NESYP,K)=BUF(NCOUNT)
  530 CONTINUE
  540 CONTINUE
      END IF
C
      IF(LCONC.EQ.1) THEN
C ... CC_MLを受信する。
C
      NDATA=2*(JNOR-JSOU-NESYM-NESYP+1)*(KTOP-KBOT+3)
     &     +2*MAX(0,IEAS-IWES-NESXM-NESXP-1)*(KTOP-KBOT+3)
C
      DO 640 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 600 K=KBOT-1,KTOP+1
      DO 600 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(5,ICHILN+1).GE.0) GO TO 600
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 600
      CC_ML(IWES+NESXM,J,K)=BUF(NCOUNT)
  600 CONTINUE
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 610 K=KBOT-1,KTOP+1
      DO 610 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(6,ICHILN+1).GE.0) GO TO 610
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 610
      CC_ML(IEAS-NESXP,J,K)=BUF(NCOUNT)
  610 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 620 K=KBOT-1,KTOP+1
      DO 620 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(4,ICHILN+1).GE.0) GO TO 620
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 620
      CC_ML(I,JSOU+NESYM,K)=BUF(NCOUNT)
  620 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 630 K=KBOT-1,KTOP+1
      DO 630 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(7,ICHILN+1).GE.0) GO TO 630
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 630
      CC_ML(I,JNOR-NESYP,K)=BUF(NCOUNT)
  630 CONTINUE
  640 CONTINUE
      END IF
C
      IF(LTURB.GE.3) THEN
C ... X1_MLを受信する。
C
      NDATA=2*(JNOR-JSOU-NESYM-NESYP+1)*(KTOP-KBOT+3)
     &     +2*MAX(0,IEAS-IWES-NESXM-NESXP-1)*(KTOP-KBOT+3)
C
      DO 740 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 700 K=KBOT-1,KTOP+1
      DO 700 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(5,ICHILN+1).GE.0) GO TO 700
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 700
      X1_ML(IWES+NESXM,J,K)=BUF(NCOUNT)
  700 CONTINUE
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 710 K=KBOT-1,KTOP+1
      DO 710 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(6,ICHILN+1).GE.0) GO TO 710
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 710
      X1_ML(IEAS-NESXP,J,K)=BUF(NCOUNT)
  710 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 720 K=KBOT-1,KTOP+1
      DO 720 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(4,ICHILN+1).GE.0) GO TO 720
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 720
      X1_ML(I,JSOU+NESYM,K)=BUF(NCOUNT)
  720 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 730 K=KBOT-1,KTOP+1
      DO 730 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(7,ICHILN+1).GE.0) GO TO 730
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 730
      X1_ML(I,JNOR-NESYP,K)=BUF(NCOUNT)
  730 CONTINUE
  740 CONTINUE
      END IF
C
      IF(LTURB.GE.3) THEN
C ... X2_MLを受信する。
C
      NDATA=2*(JNOR-JSOU-NESYM-NESYP+1)*(KTOP-KBOT+3)
     &     +2*MAX(0,IEAS-IWES-NESXM-NESXP-1)*(KTOP-KBOT+3)
C
      DO 840 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 800 K=KBOT-1,KTOP+1
      DO 800 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(5,ICHILN+1).GE.0) GO TO 800
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 800
      X2_ML(IWES+NESXM,J,K)=BUF(NCOUNT)
      IF(BUF(NCOUNT).GE.1.0D30) THEN
        X2_ML(IWES+NESXM,J,K) = X2_ML(IWES+NESXM-1,J,K)
      END IF
  800 CONTINUE
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 810 K=KBOT-1,KTOP+1
      DO 810 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(6,ICHILN+1).GE.0) GO TO 810
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 810
      X2_ML(IEAS-NESXP,J,K)=BUF(NCOUNT)
      IF(BUF(NCOUNT).GE.1.0D30) THEN
        X2_ML(IEAS-NESXP,J,K) = X2_ML(IEAS-NESXP+1,J,K)
      END IF
  810 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 820 K=KBOT-1,KTOP+1
      DO 820 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(4,ICHILN+1).GE.0) GO TO 820
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 820
      X2_ML(I,JSOU+NESYM,K)=BUF(NCOUNT)
      IF(BUF(NCOUNT).GE.1.0D30) THEN
        X2_ML(I,JSOU+NESYM,K) = X2_ML(I,JSOU+NESYM-1,K)
      END IF
  820 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 830 K=KBOT-1,KTOP+1
      DO 830 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(7,ICHILN+1).GE.0) GO TO 830
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 830
      X2_ML(I,JNOR-NESYP,K)=BUF(NCOUNT)
      IF(BUF(NCOUNT).GE.1.0D30) THEN
        X2_ML(I,JNOR-NESYP,K) = X2_ML(I,JNOR-NESYP+1,K)
      END IF
  830 CONTINUE
  840 CONTINUE
      END IF
C
      IF(LSEDI.EQ.1) THEN
C ... CSD_MLを受信する。
C
      NDATA=2*(JNOR-JSOU-NESYM-NESYP+1)*(KTOP-KBOT+3)
     &     +2*MAX(0,IEAS-IWES-NESXM-NESXP-1)*(KTOP-KBOT+3)
C
      DO 940 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 900 K=KBOT-1,KTOP+1
      DO 900 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(5,ICHILN+1).GE.0) GO TO 900
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 900
      CSD_ML(IWES+NESXM,J,K)=BUF(NCOUNT)
  900 CONTINUE
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 910 K=KBOT-1,KTOP+1
      DO 910 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(6,ICHILN+1).GE.0) GO TO 910
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 910
      CSD_ML(IEAS-NESXP,J,K)=BUF(NCOUNT)
  910 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 920 K=KBOT-1,KTOP+1
      DO 920 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(4,ICHILN+1).GE.0) GO TO 920
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 920
      CSD_ML(I,JSOU+NESYM,K)=BUF(NCOUNT)
  920 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 930 K=KBOT-1,KTOP+1
      DO 930 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(7,ICHILN+1).GE.0) GO TO 930
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 930
      CSD_ML(I,JNOR-NESYP,K)=BUF(NCOUNT)
  930 CONTINUE
  940 CONTINUE
C
C ... ZBD_MLを受信する。
C
      NDATA=2*(JNOR-JSOU-NESYM-NESYP+1)
     &     +2*MAX(0,IEAS-IWES-NESXM-NESXP-1)
C
      DO 990 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 950 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(5,ICHILN+1).GE.0) GO TO 950
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 950
      ZBD_ML(IWES+NESXM,J)=BUF(NCOUNT)
  950 CONTINUE
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 960 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(6,ICHILN+1).GE.0) GO TO 960
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 960
      ZBD_ML(IEAS-NESXP,J)=BUF(NCOUNT)
  960 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 970 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(4,ICHILN+1).GE.0) GO TO 970
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 970
      ZBD_ML(I,JSOU+NESYM)=BUF(NCOUNT)
  970 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 980 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(7,ICHILN+1).GE.0) GO TO 980
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 980
      ZBD_ML(I,JNOR-NESYP)=BUF(NCOUNT)
  980 CONTINUE
  990 CONTINUE
C
      END IF
C
C ...............
      END IF
C ...............
      RETURN
      END
