      SUBROUTINE CP_RCVQBCNS2ML(QBXC_ML,QBYC_ML,BUF,MX_ML,MY_ML,MZ_ML,
     $                          IEAS,IWES,JSOU,JNOR,
     $                          NESXM,NESXP,NESYM,NESYP)
C----------------------------------------------------------------------
C     NS側で平均化した掃流砂量を受信する
C----------------------------------------------------------------------
C
      use mod_comm,only: comm_model
      IMPLICIT NONE
C
      INCLUDE  'CP_NESTBC.h'
      INCLUDE  'CONNEC.h'
      INCLUDE  'mpif.h'
      INCLUDE  'GLOBAL.h'
C
      INTEGER,INTENT(IN)::MX_ML,MY_ML,MZ_ML
      INTEGER,INTENT(IN)::IEAS,IWES,JSOU,JNOR
      INTEGER,INTENT(IN)::NESXM,NESXP,NESYM,NESYP
      REAL(8),INTENT(INOUT)::QBXC_ML(MX_ML,MY_ML)
      REAL(8),INTENT(INOUT)::QBYC_ML(MX_ML,MY_ML)
      REAL(8),INTENT(INOUT)::BUF(*)
C
      INTEGER::ISTAT(MPI_STATUS_SIZE)
C
      INTEGER::I,ICHILD,IERROR,IREQ,J,K,NCOUNT,NDATA
      INTEGER::N,NS,NE,ICHILN,JSS,JEE,ISS,IEE
C
      NS = NUMPE(2,NRANK+1)
      NE = NS+NUMPE(1,NRANK+1)-1
C
      NDATA=2*(JNOR-JSOU-NESYM-NESYP+1)
     &     +2*MAX(0,IEAS-IWES-NESXM-NESXP-1)
C
C
C ... QBXC_MLを受信する。
C
      DO 100 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 110 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(5,ICHILN+1).GE.0) GO TO 110
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 110
      QBXC_ML(IWES+NESXM,J)=BUF(NCOUNT)
  110 CONTINUE
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 120 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(6,ICHILN+1).GE.0) GO TO 120
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 120
      QBXC_ML(IEAS-NESXP,J)=BUF(NCOUNT)
  120 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 130 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(4,ICHILN+1).GE.0) GO TO 130
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 130
      QBXC_ML(I,JSOU+NESYM)=BUF(NCOUNT)
  130 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 140 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(7,ICHILN+1).GE.0) GO TO 140
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 140
      QBXC_ML(I,JNOR-NESYP)=BUF(NCOUNT)
  140 CONTINUE
  100 CONTINUE
C
C
C ... QBYC_MLを受信する。
C
      DO 200 N=NS,NE
      ICHILN = NUMCOM(1,N)
      CALL MPI_IRECV(BUF,NDATA,MPI_DOUBLE_PRECISION,ICHILN,
     &               MPI_ANY_TAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      NCOUNT=0
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 210 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(5,ICHILN+1).GE.0) GO TO 210
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 210
      QBYC_ML(IWES+NESXM,J)=BUF(NCOUNT)
  210 CONTINUE
C
      JSS = JSOU+NESYM
      JEE = JNOR-NESYP
      IF(IPECON(4,ICHILN+1).GE.0) JSS=INDCM2(3,N-NS+1)
      IF(IPECON(7,ICHILN+1).GE.0) JEE=INDCM2(4,N-NS+1)
      DO 220 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      IF(IPECON(6,ICHILN+1).GE.0) GO TO 220
      IF(J.LT.JSS.OR.J.GT.JEE   ) GO TO 220
      QBYC_ML(IEAS-NESXP,J)=BUF(NCOUNT)
  220 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 230 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(4,ICHILN+1).GE.0) GO TO 230
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 230
      QBYC_ML(I,JSOU+NESYM)=BUF(NCOUNT)
  230 CONTINUE
C
      ISS = IWES+NESXM+1
      IEE = IEAS-NESXP-1
      IF(IPECON(5,ICHILN+1).GE.0) ISS=INDCM2(1,N-NS+1)
      IF(IPECON(6,ICHILN+1).GE.0) IEE=INDCM2(2,N-NS+1)
      DO 240 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IF(IPECON(7,ICHILN+1).GE.0) GO TO 240
      IF(I.LT.ISS.OR.I.GT.IEE   ) GO TO 240
      QBYC_ML(I,JNOR-NESYP)=BUF(NCOUNT)
  240 CONTINUE
  200 CONTINUE
C
      RETURN
      END
