      SUBROUTINE CP_SNDQBCML2NS(MX_ML,MY_ML,IEAS,IWES,JSOU,JNOR,BUF,
     $                          ZBED_ML,QBXC_ML,QBYC_ML)
C----------------------------------------------------------------------
C     MLの境界におけるセル中心掃流砂量をNSに転送する
C----------------------------------------------------------------------
C
      use mod_comm,only: comm_model
      IMPLICIT NONE
C
      INCLUDE  'mpif.h'
      INCLUDE  'CONNEC.h'
C
      INTEGER,INTENT(INOUT)::MX_ML,MY_ML
      INTEGER,INTENT(INOUT)::IEAS,IWES,JSOU,JNOR
C
      REAL(8),INTENT(INOUT)::ZBED_ML(MX_ML,MY_ML)
      REAL(8),INTENT(INOUT)::QBXC_ML(MX_ML,MY_ML)
      REAL(8),INTENT(INOUT)::QBYC_ML(MX_ML,MY_ML)
      REAL(8),INTENT(INOUT)::BUF(*)
C
      INTEGER::ISTAT(MPI_STATUS_SIZE)
C
      INTEGER::I,ICHILN,IERROR,IREQ,ITAG,J,NCOUNT
      INTEGER::N,NE,NS
C
      NS=NUMPE(2,NRANK+1)
      NE=NUMPE(1,NRANK+1)+NS-1
C
      ITAG=0  
C
C
C ... 子にQBXC_MLを送信する。
      NCOUNT=0
C
      DO 100 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(IWES-1,J)
  100 CONTINUE
C
      DO 110 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(IWES,J)
  110 CONTINUE
C
      DO 120 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(IEAS,J)
  120 CONTINUE
C
      DO 130 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(IEAS+1,J)
  130 CONTINUE
C
      DO 140 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(I,JSOU-1)
  140 CONTINUE
C
      DO 150 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(I,JSOU)
  150 CONTINUE
C
      DO 160 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(I,JNOR)
  160 CONTINUE
C
      DO 170 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(I,JNOR+1)
  170 CONTINUE
C
      DO 180 N=NS,NE
      ICHILN=NUMCOM(1,N)
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,ICHILN,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
  180 CONTINUE
C
C
C ... 子にQBYC_MLを送信する。
      NCOUNT=0
C
      DO 200 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(IWES-1,J)
  200 CONTINUE
C
      DO 210 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(IWES,J)
  210 CONTINUE
C
      DO 220 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(IEAS,J)
  220 CONTINUE
C
      DO 230 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(IEAS+1,J)
  230 CONTINUE
C
      DO 240 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(I,JSOU-1)
  240 CONTINUE
C
      DO 250 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(I,JSOU)
  250 CONTINUE
C
      DO 260 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(I,JNOR)
  260 CONTINUE
C
      DO 270 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(I,JNOR+1)
  270 CONTINUE
C
      DO 280 N=NS,NE
      ICHILN=NUMCOM(1,N)
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,ICHILN,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
  280 CONTINUE
C
C
C ... 子にZBED_MLを送信する。
      NCOUNT=0
C
      DO 300 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBED_ML(IWES-1,J)
  300 CONTINUE
C
      DO 310 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBED_ML(IWES,J)
  310 CONTINUE
C
      DO 320 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBED_ML(IEAS,J)
  320 CONTINUE
C
      DO 330 J=JSOU-1,JNOR+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBED_ML(IEAS+1,J)
  330 CONTINUE
C
      DO 340 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBED_ML(I,JSOU-1)
  340 CONTINUE
C
      DO 350 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBED_ML(I,JSOU)
  350 CONTINUE
C
      DO 360 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBED_ML(I,JNOR)
  360 CONTINUE
C
      DO 370 I=IWES+1,IEAS-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBED_ML(I,JNOR+1)
  370 CONTINUE
C
      DO 380 N=NS,NE
      ICHILN=NUMCOM(1,N)
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,ICHILN,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
  380 CONTINUE
C
      RETURN
      END
