      SUBROUTINE CP_SNDQBCNS2ML(QBXC_ML,QBYC_ML,BUF,MX_ML,MY_ML,MZ_ML,
     $                          IEAS,IWES,JSOU,JNOR,
     $                          NESXM,NESXP,NESYM,NESYP)
C----------------------------------------------------------------------
C     NS側で平均化した掃流砂量をMLに送信する
C----------------------------------------------------------------------
C
      use mod_comm,only: comm_model
      IMPLICIT NONE
C
      INCLUDE  'CP_NESTBC.h'
      INCLUDE  'CONNEC.h'
      INCLUDE  'mpif.h'
C
      INTEGER,INTENT(IN)::MX_ML,MY_ML,MZ_ML
      INTEGER,INTENT(IN)::IEAS,IWES,JSOU,JNOR
      INTEGER,INTENT(IN)::NESXM,NESXP,NESYM,NESYP
      REAL(8),INTENT(IN)::QBXC_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1),
     $                    QBYC_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1)
      REAL(8),INTENT(INOUT)::BUF(*)
C ... ローカル変数
      INTEGER::I,J
      INTEGER::ISTAT(MPI_STATUS_SIZE)
      INTEGER::IERROR,IPARNT,IREQ,ITAG,NCOUNT
C
      IPARNT=IPECON(2,NRANK+1)
C
      ITAG=0
C
C ... 親にQBXC_MLを送信する。
C
      NCOUNT=0
C
      DO 100 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(IWES+NESXM,J)
  100 CONTINUE
C
      DO 110 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(IEAS-NESXP,J)
  110 CONTINUE
C
      DO 120 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(I,JSOU+NESYM)
  120 CONTINUE
C
      DO 130 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBXC_ML(I,JNOR-NESYP)
  130 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
C
C ... 親にQBYC_MLを送信する。
C
      NCOUNT=0
C
      DO 200 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(IWES+NESXM,J)
  200 CONTINUE
C
      DO 210 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(IEAS-NESXP,J)
  210 CONTINUE
C
      DO 220 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(I,JSOU+NESYM)
  220 CONTINUE
C
      DO 230 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=QBYC_ML(I,JNOR-NESYP)
  230 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
C
      RETURN
      END
