      SUBROUTINE CP_SNDNS2ML(UU_ML,VV_ML,WW_ML,TT_ML,CC_ML,X1_ML,X2_ML,
     1                       HH_ML,CSD_ML,ZBD_ML,BUF,
     2                       MX_ML,MY_ML,MZ_ML,
     3                       IEAS,IWES,JSOU,JNOR,KBOT,KTOP,
     4                       NESXM,NESXP,NESYM,NESYP,IFL)
C-----------------------------------------------------------------------
C     NS側で平均化した流速,潮位をMLに送信する
C       LTURB=3 : X1=Q2,X2=QL
C       LTURB=4 : X1=AK,X2=1.0D30
C-----------------------------------------------------------------------
C
      use mod_comm,only: comm_model
      IMPLICIT NONE
C
      INCLUDE  'MODELI.h'
      INCLUDE  'CP_NESTBC.h'
      INCLUDE  'CONNEC.h'
      INCLUDE  'mpif.h'
C
      INTEGER,INTENT(INOUT)::MX_ML,MY_ML,MZ_ML
      INTEGER,INTENT(INOUT)::IEAS,IWES,JSOU,JNOR,KBOT,KTOP
      INTEGER,INTENT(INOUT)::NESXM,NESXP,NESYM,NESYP
      INTEGER,INTENT(INOUT)::IFL
C
      REAL(8),INTENT(INOUT)::
     $   UU_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1,KBOT-1:KTOP+1),
     $   VV_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1,KBOT-1:KTOP+1),
     $   WW_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1,KBOT-1:KTOP+1),
     $   TT_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1,KBOT-1:KTOP+1),
     $   CC_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1,KBOT-1:KTOP+1),
     $   CSD_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1,KBOT-1:KTOP+1),
     $   ZBD_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1),
     $   X1_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1,KBOT-1:KTOP+1),
     $   X2_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1,KBOT-1:KTOP+1),
     $   HH_ML(IWES-1:IEAS+1,JSOU-1:JNOR+1)
      REAL(8),INTENT(INOUT)::BUF(*)
C
      INTEGER::ISTAT(MPI_STATUS_SIZE)
C
      INTEGER::I,IERROR,IPARNT,IREQ,ITAG,J,K,NCOUNT
C
      IPARNT=IPECON(2,NRANK+1)
C
      ITAG=0
C ... IFL = 1 UU_ML,VV_MLのみを送信
      IF(IFL.EQ.1.OR.IFL.EQ.0) THEN
C ...................................
C
C ... 親にUU_MLを送信する。
C
      NCOUNT=0
C
      IF(NESXM.GT.0) THEN
         DO 100 K=KBOT-1,KTOP+1
         DO 100 J=JSOU+NESYM,JNOR-NESYP
         NCOUNT=NCOUNT+1
         BUF(NCOUNT)=UU_ML(IWES+NESXM-1,J,K)
  100    CONTINUE
      ENDIF
C
      IF(NESXP.GT.0) THEN
         DO 110 K=KBOT-1,KTOP+1
         DO 110 J=JSOU+NESYM,JNOR-NESYP
         NCOUNT=NCOUNT+1
         BUF(NCOUNT)=UU_ML(IEAS-NESXP,J,K)
  110    CONTINUE
      ENDIF
C
      DO 120 K=KBOT-1,KTOP+1
      DO 120 I=IWES+NESXM,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=UU_ML(I,JSOU+NESYM,K)
  120 CONTINUE
C
      DO 130 K=KBOT-1,KTOP+1
      DO 130 I=IWES+NESXM,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=UU_ML(I,JNOR-NESYP,K)
  130 CONTINUE
C
      IF(NCOUNT.GT.0) THEN
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
      ENDIF
C
C ... 親にVV_MLを送信する。
C
      NCOUNT=0
C
      IF(NESYM.GT.0) THEN
         DO 200 K=KBOT-1,KTOP+1
         DO 200 I=IWES+NESXM,IEAS-NESXP
         NCOUNT=NCOUNT+1
         BUF(NCOUNT)=VV_ML(I,JSOU+NESYM-1,K)
  200    CONTINUE
      ENDIF
C
      IF(NESYP.GT.0) THEN
         DO 210 K=KBOT-1,KTOP+1
         DO 210 I=IWES+NESXM,IEAS-NESXP
         NCOUNT=NCOUNT+1
         BUF(NCOUNT)=VV_ML(I,JNOR-NESYP,K)
  210    CONTINUE
      ENDIF
C
      DO 220 K=KBOT-1,KTOP+1
      DO 220 J=JSOU+NESYM,JNOR-NESYP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=VV_ML(IWES+NESXM,J,K)
  220 CONTINUE
C
      DO 230 K=KBOT-1,KTOP+1
      DO 230 J=JSOU+NESYM,JNOR-NESYP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=VV_ML(IEAS-NESXP,J,K)
  230 CONTINUE
C
      IF(NCOUNT.GT.0) THEN
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
      ENDIF
C
      END IF
C
C ... IFL = 2 (UU_ML,VV_ML)以外を送信
      IF(IFL.EQ.2.OR.IFL.EQ.0) THEN
C .....................................
C
C ... 親にWW_MLを送信する。
C
      NCOUNT=0
C
      DO 300 K=KBOT-1,KTOP+1
      DO 300 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=WW_ML(IWES+NESXM,J,K)
  300 CONTINUE
C
      DO 310 K=KBOT-1,KTOP+1
      DO 310 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=WW_ML(IEAS-NESXP,J,K)
  310 CONTINUE
C
      DO 320 K=KBOT-1,KTOP+1
      DO 320 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=WW_ML(I,JSOU+NESYM,K)
  320 CONTINUE
C
      DO 330 K=KBOT-1,KTOP+1
      DO 330 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=WW_ML(I,JNOR-NESYP,K)
  330 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
C ... 子にHH_MLを送信する。
C
      NCOUNT=0
      DO 400 J=JSOU-1,JNOR+1
      DO 400 I=IWES-1,IWES+NESXM
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=HH_ML(I,J)
  400 CONTINUE
C
      DO 410 J=JSOU-1,JNOR+1
      DO 410 I=IEAS-NESXP,IEAS+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=HH_ML(I,J)
  410 CONTINUE
C
      DO 420 J=JSOU-1,JSOU+NESYM
      DO 420 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=HH_ML(I,J)
  420 CONTINUE
C
      DO 430 J=JNOR-NESYP,JNOR+1
      DO 430 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=HH_ML(I,J)
  430 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      IF(LTEMP.EQ.1) THEN
C ... 親にTT_MLを送信する。
C
      NCOUNT=0
C
      DO 500 K=KBOT-1,KTOP+1
      DO 500 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=TT_ML(IWES+NESXM,J,K)
  500 CONTINUE
C
      DO 510 K=KBOT-1,KTOP+1
      DO 510 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=TT_ML(IEAS-NESXP,J,K)
  510 CONTINUE
C
      DO 520 K=KBOT-1,KTOP+1
      DO 520 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=TT_ML(I,JSOU+NESYM,K)
  520 CONTINUE
C
      DO 530 K=KBOT-1,KTOP+1
      DO 530 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=TT_ML(I,JNOR-NESYP,K)
  530 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
      END IF
C
      IF(LCONC.EQ.1) THEN
C ... 親にCC_MLを送信する。
C
      NCOUNT=0
C
      DO 600 K=KBOT-1,KTOP+1
      DO 600 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=CC_ML(IWES+NESXM,J,K)
  600 CONTINUE
C
      DO 610 K=KBOT-1,KTOP+1
      DO 610 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=CC_ML(IEAS-NESXP,J,K)
  610 CONTINUE
C
      DO 620 K=KBOT-1,KTOP+1
      DO 620 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=CC_ML(I,JSOU+NESYM,K)
  620 CONTINUE
C
      DO 630 K=KBOT-1,KTOP+1
      DO 630 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=CC_ML(I,JNOR-NESYP,K)
  630 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
      END IF
C
      IF(LTURB.GE.3) THEN
C ... 親にX1_MLを送信する。
C
      NCOUNT=0
C
      DO 700 K=KBOT-1,KTOP+1
      DO 700 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=X1_ML(IWES+NESXM,J,K)
  700 CONTINUE
C
      DO 710 K=KBOT-1,KTOP+1
      DO 710 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=X1_ML(IEAS-NESXP,J,K)
  710 CONTINUE
C
      DO 720 K=KBOT-1,KTOP+1
      DO 720 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=X1_ML(I,JSOU+NESYM,K)
  720 CONTINUE
C
      DO 730 K=KBOT-1,KTOP+1
      DO 730 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=X1_ML(I,JNOR-NESYP,K)
  730 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
      END IF
C
      IF(LTURB.EQ.3) THEN 
C ... 親にX2_MLを送信する。
C
      NCOUNT=0
C
      DO 800 K=KBOT-1,KTOP+1
      DO 800 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=X2_ML(IWES+NESXM,J,K)
  800 CONTINUE
C
      DO 810 K=KBOT-1,KTOP+1
      DO 810 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=X2_ML(IEAS-NESXP,J,K)
  810 CONTINUE
C
      DO 820 K=KBOT-1,KTOP+1
      DO 820 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=X2_ML(I,JSOU+NESYM,K)
  820 CONTINUE
C
      DO 830 K=KBOT-1,KTOP+1
      DO 830 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=X2_ML(I,JNOR-NESYP,K)
  830 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
      ELSE IF(LTURB.EQ.4) THEN
C ... 親にX2_ML（ダミー）を送信する。
C
      NCOUNT=0
C
      DO 840 K=KBOT-1,KTOP+1
      DO 840 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=1.0D30
  840 CONTINUE
C
      DO 850 K=KBOT-1,KTOP+1
      DO 850 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=1.0D30
  850 CONTINUE
C
      DO 860 K=KBOT-1,KTOP+1
      DO 860 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=1.0D30
  860 CONTINUE
C
      DO 870 K=KBOT-1,KTOP+1
      DO 870 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=1.0D30
  870 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
      END IF
C
      IF(LSEDI.EQ.1) THEN
C ... 親にCSD_MLを送信する。
C
      NCOUNT=0
C
      DO 900 K=KBOT-1,KTOP+1
      DO 900 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=CSD_ML(IWES+NESXM,J,K)
  900 CONTINUE
C
      DO 910 K=KBOT-1,KTOP+1
      DO 910 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=CSD_ML(IEAS-NESXP,J,K)
  910 CONTINUE
C
      DO 920 K=KBOT-1,KTOP+1
      DO 920 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=CSD_ML(I,JSOU+NESYM,K)
  920 CONTINUE
C
      DO 930 K=KBOT-1,KTOP+1
      DO 930 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=CSD_ML(I,JNOR-NESYP,K)
  930 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
C ... 子にZBD_MLを送信する。
C
      NCOUNT=0
C
      DO 940 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBD_ML(IWES+NESXM,J)
  940 CONTINUE
C
      DO 950 J=JSOU+NESYM,JNOR-NESYP
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBD_ML(IEAS-NESXP,J)
  950 CONTINUE
C
      DO 960 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBD_ML(I,JSOU+NESYM)
  960 CONTINUE
C
      DO 970 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=ZBD_ML(I,JNOR-NESYP)
  970 CONTINUE
C
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,IPARNT,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
C
C
      END IF
C
C ...............
      END IF
C ...............
      RETURN
      END
