      SUBROUTINE CP_SNDIND(INDU_ML,INDV_ML,INDW_ML,INDP_ML,IBUF,
     1                     GX_ML,GY_ML,GZ_ML,GV_ML,BUF,
     2                     MX_ML,MY_ML,MZ_ML,
     3                     IEAS,IWES,JSOU,JNOR,KBOT,KTOP,
     4                     NESXM,NESXP,NESYM,NESYP)
C-----------------------------------------------------------------------
C     IPFLG=0 : MLのINDU,INDV,INDW,GX,GY,GZをNSに転送する
C     IPFLG=1 : MLのINDU,INDV,INDW,GX,GY,GZをファイルに出力する
C-----------------------------------------------------------------------
C
      use mod_comm,only: comm_model
      IMPLICIT NONE
C
      INCLUDE  'CP_NESTBC.h'
      INCLUDE  'CONNEC.h'
      INCLUDE  'FILE.h'
      INCLUDE  'OUTPUT.h'
      INCLUDE  'mpif.h'
C
      INTEGER,INTENT(INOUT)::MX_ML,MY_ML,MZ_ML
      INTEGER,INTENT(INOUT)::IEAS,IWES,JSOU,JNOR,KBOT,KTOP
      INTEGER,INTENT(INOUT)::NESXM,NESXP,NESYM,NESYP
C
      INTEGER,INTENT(INOUT)::INDU_ML(MX_ML,MY_ML,MZ_ML)
      INTEGER,INTENT(INOUT)::INDV_ML(MX_ML,MY_ML,MZ_ML)
      INTEGER,INTENT(INOUT)::INDW_ML(MX_ML,MY_ML,MZ_ML)
      INTEGER,INTENT(INOUT)::INDP_ML(MX_ML,MY_ML,MZ_ML)
      INTEGER,INTENT(INOUT)::IBUF(*)
C
      REAL(8),INTENT(INOUT)::GX_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::GY_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::GZ_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::GV_ML(MX_ML,MY_ML,MZ_ML)
      REAL(8),INTENT(INOUT)::BUF(*)
C
      INTEGER::ISTAT(MPI_STATUS_SIZE)
C
C     INTEGER::I,ICHILD,IERROR,IREQ,ITAG,J,K,NCOUNT
      INTEGER::I,ICHILN,IERROR,IREQ,ITAG,J,K,NCOUNT
      INTEGER::N,NE,NS
C
C     ICHILD=IPECON(3,NRANK+1)
      NS=NUMPE(2,NRANK+1)
      NE=NUMPE(1,NRANK+1)+NS-1
C
      ITAG=0
C
C ... 子にINDU_MLを送信する。
C
      NCOUNT=0
      DO 100 K=KBOT-1,KTOP+1
      DO 100 J=JSOU-1,JNOR+1
      DO 100 I=IWES-1,IWES+NESXM
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDU_ML(I,J,K)
  100 CONTINUE
C
      DO 110 K=KBOT-1,KTOP+1
      DO 110 J=JSOU-1,JNOR+1
      DO 110 I=IEAS-NESXP,IEAS+1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDU_ML(I,J,K)
  110 CONTINUE
C
      DO 120 K=KBOT-1,KTOP+1
      DO 120 J=JSOU-1,JSOU+NESYM
      DO 120 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDU_ML(I,J,K)
  120 CONTINUE
C
      DO 130 K=KBOT-1,KTOP+1
      DO 130 J=JNOR-NESYP,JNOR+1
      DO 130 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDU_ML(I,J,K)
  130 CONTINUE
C
      DO 140 N=NS,NE
      ICHILN=NUMCOM(1,N)
      CALL MPI_ISEND(IBUF,NCOUNT,MPI_INTEGER,ICHILN,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
  140 CONTINUE
C
      IF(RFILE(3).GT.0.0D0) THEN
        WRITE(IFLBO) NCOUNT,(IBUF(N),N=1,NCOUNT)
      END IF
C
C ... 子にINDV_MLを送信する。
C
      NCOUNT=0
      DO 200 K=KBOT-1,KTOP+1
      DO 200 J=JSOU-1,JNOR+1
      DO 200 I=IWES-1,IWES+NESXM
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDV_ML(I,J,K)
  200 CONTINUE
C
      DO 210 K=KBOT-1,KTOP+1
      DO 210 J=JSOU-1,JNOR+1
      DO 210 I=IEAS-NESXP,IEAS+1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDV_ML(I,J,K)
  210 CONTINUE
C
      DO 220 K=KBOT-1,KTOP+1
      DO 220 J=JSOU-1,JSOU+NESYM
      DO 220 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDV_ML(I,J,K)
  220 CONTINUE
C
      DO 230 K=KBOT-1,KTOP+1
      DO 230 J=JNOR-NESYP,JNOR+1
      DO 230 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDV_ML(I,J,K)
  230 CONTINUE
C
      DO 240 N=NS,NE
      ICHILN=NUMCOM(1,N)
      CALL MPI_ISEND(IBUF,NCOUNT,MPI_INTEGER,ICHILN,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
  240 CONTINUE
C
      IF(RFILE(3).GT.0.0D0) THEN
        WRITE(IFLBO) NCOUNT,(IBUF(N),N=1,NCOUNT)
      END IF
C
C ... 子にINDW_MLを送信する。
C
      NCOUNT=0
      DO 300 K=KBOT-1,KTOP+1
      DO 300 J=JSOU-1,JNOR+1
      DO 300 I=IWES-1,IWES+NESXM
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDW_ML(I,J,K)
  300 CONTINUE
C
      DO 310 K=KBOT-1,KTOP+1
      DO 310 J=JSOU-1,JNOR+1
      DO 310 I=IEAS-NESXP,IEAS+1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDW_ML(I,J,K)
  310 CONTINUE
C
      DO 320 K=KBOT-1,KTOP+1
      DO 320 J=JSOU-1,JSOU+NESYM
      DO 320 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDW_ML(I,J,K)
  320 CONTINUE
C
      DO 330 K=KBOT-1,KTOP+1
      DO 330 J=JNOR-NESYP,JNOR+1
      DO 330 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDW_ML(I,J,K)
  330 CONTINUE
C
      DO 340 N=NS,NE
      ICHILN=NUMCOM(1,N)
      CALL MPI_ISEND(IBUF,NCOUNT,MPI_INTEGER,ICHILN,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
  340 CONTINUE
      IF(RFILE(3).GT.0.0D0) THEN
        WRITE(IFLBO) NCOUNT,(IBUF(N),N=1,NCOUNT)
      END IF
C
C ... 子にINDP_MLを送信する。
C
      NCOUNT=0
      DO 700 K=KBOT-1,KTOP+1
      DO 700 J=JSOU-1,JNOR+1
      DO 700 I=IWES-1,IWES+NESXM
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDP_ML(I,J,K)
  700 CONTINUE
C
      DO 710 K=KBOT-1,KTOP+1
      DO 710 J=JSOU-1,JNOR+1
      DO 710 I=IEAS-NESXP,IEAS+1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDP_ML(I,J,K)
  710 CONTINUE
C
      DO 720 K=KBOT-1,KTOP+1
      DO 720 J=JSOU-1,JSOU+NESYM
      DO 720 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDP_ML(I,J,K)
  720 CONTINUE
C
      DO 730 K=KBOT-1,KTOP+1
      DO 730 J=JNOR-NESYP,JNOR+1
      DO 730 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      IBUF(NCOUNT)=INDP_ML(I,J,K)
  730 CONTINUE
C
      DO 740 N=NS,NE
      ICHILN=NUMCOM(1,N)
      CALL MPI_ISEND(IBUF,NCOUNT,MPI_INTEGER,ICHILN,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
  740 CONTINUE
C
      IF(RFILE(3).GT.0.0D0) THEN
        WRITE(IFLBO) NCOUNT,(IBUF(N),N=1,NCOUNT)
      END IF
C
C ... 子にGX_MLを送信する。
C
      NCOUNT=0
      DO 400 K=KBOT-1,KTOP+1
      DO 400 J=JSOU-1,JNOR+1
      DO 400 I=IWES-1,IWES+NESXM
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GX_ML(I,J,K)
  400 CONTINUE
C
      DO 410 K=KBOT-1,KTOP+1
      DO 410 J=JSOU-1,JNOR+1
      DO 410 I=IEAS-NESXP,IEAS+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GX_ML(I,J,K)
  410 CONTINUE
C
      DO 420 K=KBOT-1,KTOP+1
      DO 420 J=JSOU-1,JSOU+NESYM
      DO 420 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GX_ML(I,J,K)
  420 CONTINUE
C
      DO 430 K=KBOT-1,KTOP+1
      DO 430 J=JNOR-NESYP,JNOR+1
      DO 430 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GX_ML(I,J,K)
  430 CONTINUE
C
      DO 440 N=NS,NE
      ICHILN=NUMCOM(1,N)
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,ICHILN,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
  440 CONTINUE
C
      IF(RFILE(3).GT.0.0D0) THEN
        WRITE(IFLBO) NCOUNT,(BUF(N),N=1,NCOUNT)
      END IF
C
C ... 子にGY_MLを送信する。
C
      NCOUNT=0
      DO 500 K=KBOT-1,KTOP+1
      DO 500 J=JSOU-1,JNOR+1
      DO 500 I=IWES-1,IWES+NESXM
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GY_ML(I,J,K)
  500 CONTINUE
C
      DO 510 K=KBOT-1,KTOP+1
      DO 510 J=JSOU-1,JNOR+1
      DO 510 I=IEAS-NESXP,IEAS+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GY_ML(I,J,K)
  510 CONTINUE
C
      DO 520 K=KBOT-1,KTOP+1
      DO 520 J=JSOU-1,JSOU+NESYM
      DO 520 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GY_ML(I,J,K)
  520 CONTINUE
C
      DO 530 K=KBOT-1,KTOP+1
      DO 530 J=JNOR-NESYP,JNOR+1
      DO 530 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GY_ML(I,J,K)
  530 CONTINUE
C
      DO 540 N=NS,NE
      ICHILN=NUMCOM(1,N)
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,ICHILN,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
  540 CONTINUE
C
      IF(RFILE(3).GT.0.0D0) THEN
        WRITE(IFLBO) NCOUNT,(BUF(N),N=1,NCOUNT)
      END IF
C
C ... 子にGZ_MLを送信する。
C
      NCOUNT=0
      DO 600 K=KBOT-1,KTOP+1
      DO 600 J=JSOU-1,JNOR+1
      DO 600 I=IWES-1,IWES+NESXM
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GZ_ML(I,J,K)
  600 CONTINUE
C
      DO 610 K=KBOT-1,KTOP+1
      DO 610 J=JSOU-1,JNOR+1
      DO 610 I=IEAS-NESXP,IEAS+1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GZ_ML(I,J,K)
  610 CONTINUE
C
      DO 620 K=KBOT-1,KTOP+1
      DO 620 J=JSOU-1,JSOU+NESYM
      DO 620 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GZ_ML(I,J,K)
  620 CONTINUE
C
      DO 630 K=KBOT-1,KTOP+1
      DO 630 J=JNOR-NESYP,JNOR+1
      DO 630 I=IWES+NESXM+1,IEAS-NESXP-1
      NCOUNT=NCOUNT+1
      BUF(NCOUNT)=GZ_ML(I,J,K)
  630 CONTINUE
C
      DO 640 N=NS,NE
      ICHILN=NUMCOM(1,N)
      CALL MPI_ISEND(BUF,NCOUNT,MPI_DOUBLE_PRECISION,ICHILN,
     *               ITAG,comm_model,IREQ,IERROR)
      CALL MPI_WAIT(IREQ,ISTAT,IERROR)
  640 CONTINUE
C
      IF(RFILE(3).GT.0.0D0) THEN
        WRITE(IFLBO) NCOUNT,(BUF(N),N=1,NCOUNT)
      END IF
C
C delete GV_ML process 20120924
C
      RETURN
      END
